name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: cache_node_modules
        with:
          path: |
            node_modules
            functions/node_modules
          key: node_modules-${{ hashFiles('package.json', 'functions/package.json') }}-14
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        working-directory: functions
      - run: yarn prettier -c .
      - run: yarn eslint . --ext js --ext ts --ext tsx
      - run: yarn tsc
      - run: touch static/main.wasm
      - run: yarn build
  build_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"
      - uses: actions/cache@v2
        id: cache_go_mod
        with:
          path: ~/go/pkg/mod
          key: go_mod-${{ hashFiles('go.sum') }}
      - run: go get
        if: steps.cache_go_mod.outputs.cache-hit != 'true'
      - run: go build -o ./static/main .
      - run: go build -o ./static/main.wasm .
        env:
          GOOS: js
          GOARCH: wasm
