name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: cache_node_modules
        with:
          path: node_modules
          key: node_modules-14-${{ hashFiles('package.json', 'yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
      - run: yarn prettier -v
      - run: yarn prettier -c .
      - run: yarn eslint . --ext js --ext ts --ext tsx
      - run: yarn tsc
      - run: touch static/main.wasm
      - run: yarn vite build
  build_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.5"
      - uses: actions/cache@v2
        id: cache_go_mod
        with:
          path: ~/go/pkg/mod
          key: go_mod-${{ hashFiles('go.sum') }}
      - run: go get
        if: steps.cache_go_mod.outputs.cache-hit != 'true'
      - run: go build -o ./static/main .
      - run: go build -o ./static/main.wasm .
        env:
          GOOS: js
          GOARCH: wasm
