name: deploy
on:
  push:
    branches:
      - master
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: GOOS=js GOARCH=wasm go build -o ./static/main.wasm .
      - run: npx vite build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: npx tsx build.ts
        working-directory: packages/functions
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/787830619763/locations/global/workloadIdentityPools/github/providers/csgo
          service_account: github-actions-cd@csgo-tokyo.iam.gserviceaccount.com
      - run: npx firebase deploy --force
