name: deploy
on:
  release:
    types: [released]
  workflow_dispatch:
concurrency:
  group: "deploy"
  cancel-in-progress: false
permissions:
  contents: "read"
  id-token: "write"
  pages: "write"
jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: GOOS=js GOARCH=wasm go build -o ./static/main.wasm .
      - run: npx vite build --base /dem/ --outDir _site
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
        id: deployment
  firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: GOOS=js GOARCH=wasm go build -o ./static/main.wasm .
      - run: npx vite build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: npx tsx build.ts
        working-directory: packages/functions
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/787830619763/locations/global/workloadIdentityPools/github/providers/csgo
          service_account: github-actions-cd@csgo-tokyo.iam.gserviceaccount.com
      - run: npx firebase deploy --force
