name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: actions/cache@v2
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - uses: actions/cache@v2
        id: cache_go_mod
        with:
          path: ~/go/pkg/mod
          key: go_mod-${{ hashFiles('go.sum') }}
      - run: go get
        if: steps.cache_go_mod.outputs.cache-hit != 'true'
      - run: yarn tsc --noEmit
      - run: go build -o ./static/main.wasm .
        env:
          GOOS: js
          GOARCH: wasm
      - run: touch ./static/sample.dem.json
      - run: yarn vite build
      - run: yarn tsc --noEmit false
        working-directory: packages/functions
      - run: yarn firebase deploy --force --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
