name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: actions/cache@v2
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
      - run: yarn prettier -c .
      - run: yarn eslint .
      - run: yarn tsc --noEmit
